# config/admins.yml

# The admins.yml file may or may not be present in the /config directory when
# Virgo is running. If this file is not present, no admin privileges are given
# to any user, logged in or not logged in.
#
# When this file is present, those users whose computing IDs are listed in this
# file have those privileges granted for the privilege group under which they
# are listed.
#
# Under a privilege group, each user is listed by <computing ID>: <name>
#
# The <name> may be left blank; it is simply for documentation of the full name
# of the person with that computing ID.

# Privilege group 'about'.
# Users who have the privilege to see detail data on the /about page.
about:
  xxx: xxx
  xxx:  xxx
  xxx:  xxx
  xxx:  xxx
  xxx:  xxx
  xxx:  xxx

# Privilege group 'all'.
# Users who have the privileges to do all of the above.
all:
  xxx:  xxx
  xxx:  xxx
  xxx:  xxx
  xxx:  xxx
  xxx:  xxx
  xxx:    xxx
  xxx:    xxx
  xxx:   xxx
